version: "3.3"
services:
  zupgram-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["sh", "-c", "./gradlew --no-daemon cleanTest test --fail-fast --console plain --stacktrace"]
    depends_on:
        - neo4j
  neo4j:
    image: "neo4j"
    environment:
      - NEO4J_AUTH=neo4j/zuppass
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7473:7473
      - 127.0.0.1:7687:7687
