FROM gradle:6.6-jdk14

ENV ROOT_FOLDER /zupgram

USER root
RUN mkdir $ROOT_FOLDER

COPY wait-for-it.sh $ROOT_FOLDER
COPY build/libs/zupgram-1.0.jar $ROOT_FOLDER/zupgram-1.0.jar

WORKDIR /$ROOT_FOLDER
